# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvode <- function(yv, times, fderiv, param, abstol = 1.e-8, reltol = 1.e-8, fjac = NULL, jacmat_ = NULL, rmumps_perm = "auto") {
    .Call(`_rsundials_cvode`, yv, times, fderiv, param, abstol, reltol, fjac, jacmat_, rmumps_perm)
}

