# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvodes <- function(yv, times, frhs, param = NULL, abstol = 1.e-8, reltol = 1.e-8, integrator_ = NULL, maxord = 0L, maxsteps = 0L, hin = 0., hmax = 0., hmin = 0., constraints = as.numeric( c()), fjac = NULL, nz = 0L, rmumps_perm_ = NULL, nroot = 0L, froot = NULL, fevent = NULL, Ns = 0L, psens = as.numeric( c()), psens_bar = as.numeric( c()), psens_list = as.integer( c()), fsens = NULL, fsens1 = NULL, sens_method_ = NULL, errconS = TRUE) {
    .Call(`_rsundials_cvodes`, yv, times, frhs, param, abstol, reltol, integrator_, maxord, maxsteps, hin, hmax, hmin, constraints, fjac, nz, rmumps_perm_, nroot, froot, fevent, Ns, psens, psens_bar, psens_list, fsens, fsens1, sens_method_, errconS)
}

get_cnst <- function(s) {
    .Call(`_rsundials_get_cnst`, s)
}

